# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(verbose_name='Time of Publication')),
                ('commenter', models.CharField(max_length=100, verbose_name='Commenter')),
                ('comment_text', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Date of Publication')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('entry_text', models.TextField(verbose_name='Entry Text')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
        ),
    ]
