# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161110_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_time',
            new_name='pub_date',
        ),
    ]
